bind 127.0.0.1
port 13001
protected-mode no
timeout 0
tcp-keepalive 300

daemonize no
supervised no
pidfile /tmp/redis_socketio.pid

loglevel notice
logfile ""

databases 16

dir /tmp

save ""
appendonly no
